services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5050:80"
    restart: unless-stopped
    # Security Enhancements
    read_only: true
    tmpfs:
      - /var/cache/nginx:uid=101,gid=101
      - /var/run:uid=101,gid=101
      - /tmp:uid=101,gid=101
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL